///|
fn Int16::narrow_sat_i16_s(i : Int16) -> I8 {
  ...
}

///|
fn Int16::narrow_sat_i16_u(i : Int16) -> I8 {
  ...
}

///|
fn Int16::add_sat_s(a : Int16, b : Int16) -> Int16 {
  ...
}

///|
fn Int16::add_sat_u(a : Int16, b : Int16) -> Int16 {
  ...
}

///|
fn Int16::sub_sat_s(a : Int16, b : Int16) -> Int16 {
  ...
}

///|
fn Int16::sub_sat_u(a : Int16, b : Int16) -> Int16 {
  ...
}

///|
fn Int16::min_s(a : Int16, b : Int16) -> Int16 {
  ...
}

///|
fn Int16::min_u(a : Int16, b : Int16) -> Int16 {
  ...
}

///|
fn Int16::max_s(a : Int16, b : Int16) -> Int16 {
  ...
}

///|
fn Int16::max_u(a : Int16, b : Int16) -> Int16 {
  ...
}

///|
fn Int16::avgr_u(a : Int16, b : Int16) -> Int16 {
  ...
}

///|
fn Int16::extend_s(a : Int16) -> Int {
  ...
}

///|
fn Int16::extend_u(a : Int16) -> Int {
  ...
}
