///|
fn Int::narrow_sat_i32_s(i : Int) -> Int16 {
  ...
}

///|
fn Int::narrow_sat_i32_u(i : Int) -> Int16 {
  ...
}

///|
fn Int::min_s(a : Int, b : Int) -> Int {
  ...
}

///|
fn Int::min_u(a : Int, b : Int) -> Int {
  ...
}

///|
fn Int::max_s(a : Int, b : Int) -> Int {
  ...
}

///|
fn Int::max_u(a : Int, b : Int) -> Int {
  ...
}

///|
fn Int::extend_s(a : Int) -> Int64 {
  ...
}

///|
fn Int::extend_u(a : Int) -> Int64 {
  ...
}
